services:
  prod:
    build:
      context: .
      target: production
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - /app/.next
  dev:
    build:
      context: .
      target: dev
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true
