apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: habit-loop-ingress-frontend
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: habit-loop-frontend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: habit-loop-frontend
                port:
                  number: 3001
