name: CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        env:
          PORT: ${{ secrets.PORT }}
        run: docker compose up -d --build prod


      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/habit-loop-frontend

      - name: Deploy to miniKube
        run: kubectl apply -f .\infrastructure/
